# Generated by Django 5.1.7 on 2025-03-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=3)),
                ('highest_point', models.IntegerField(default=0)),
                ('lowest_point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('won', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('third', models.IntegerField(default=0)),
                ('fourth', models.IntegerField(default=0)),
                ('fifth', models.IntegerField(default=0)),
                ('sixth', models.IntegerField(default=0)),
                ('seventh', models.IntegerField(default=0)),
                ('eighth', models.IntegerField(default=0)),
                ('ninth', models.IntegerField(default=0)),
                ('tenth', models.IntegerField(default=0)),
                ('eleventh', models.IntegerField(default=0)),
                ('series_form', models.CharField(default='', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.team')),
            ],
        ),
    ]
