# Generated by Django 5.1.7 on 2025-03-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='highest_point',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lowest_point',
        ),
    ]
