# Generated by Django 5.1.7 on 2025-03-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0002_remove_team_highest_point_remove_team_lowest_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='short_name',
        ),
    ]
