# Generated by Django 5.1.7 on 2025-03-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0003_remove_team_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='eighth',
        ),
        migrations.RemoveField(
            model_name='match',
            name='eleventh',
        ),
        migrations.RemoveField(
            model_name='match',
            name='fifth',
        ),
        migrations.RemoveField(
            model_name='match',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ninth',
        ),
        migrations.RemoveField(
            model_name='match',
            name='second',
        ),
        migrations.RemoveField(
            model_name='match',
            name='seventh',
        ),
        migrations.RemoveField(
            model_name='match',
            name='sixth',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tenth',
        ),
        migrations.RemoveField(
            model_name='match',
            name='third',
        ),
        migrations.RemoveField(
            model_name='match',
            name='won',
        ),
    ]
