# Generated by Django 5.1.7 on 2025-03-23 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0004_remove_match_eighth_remove_match_eleventh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='points',
        ),
        migrations.RemoveField(
            model_name='match',
            name='series_form',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team',
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('series_form', models.CharField(choices=[('W', 'Win'), ('L', 'Lose')], default='L', max_length=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.team')),
            ],
        ),
    ]
