# Generated by Django 5.1.7 on 2025-03-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0005_remove_match_points_remove_match_series_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
